# Generated by Django 5.2.3 on 2025-06-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForSaleBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('type', models.CharField(choices=[('mtb', 'Горный'), ('road', 'Шоссейный'), ('bmx', 'BMX'), ('city', 'Городской'), ('other', 'Другой')], max_length=20, verbose_name='Тип')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена (сом)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('contact', models.CharField(max_length=100, verbose_name='Контакт (номер или Instagram)')),
                ('photo', models.ImageField(upload_to='forsale/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
