# Generated by Django 5.2.3 on 2026-01-17 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bikes/')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.forsalebike')),
            ],
        ),
    ]
