# Generated by Django 5.2.3 on 2025-06-27 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_forsalebike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forsalebike',
            name='description',
        ),
        migrations.RemoveField(
            model_name='forsalebike',
            name='photo',
        ),
        migrations.AddField(
            model_name='forsalebike',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
        migrations.AlterField(
            model_name='forsalebike',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='forsalebike',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='forsalebike',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='forsalebike',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='forsalebike',
            name='type',
            field=models.CharField(choices=[('road', 'Шоссейный'), ('mtb', 'Горный'), ('bmx', 'BMX'), ('fixie', 'Фикс'), ('other', 'Другой')], max_length=20),
        ),
        migrations.CreateModel(
            name='BikePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bikes/extra_photos/')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.forsalebike')),
            ],
        ),
    ]
